"""Utility functions for Resume Vault."""

from app.models.user_master_profile import UserMasterProfile
from app.models.company import Company


def mock_tailor_resume(profile: UserMasterProfile, company: Company) -> str:
    """
    Mock Tailor Function - Creates a basic text merge of profile and job description.

    This is a placeholder function that will be replaced with AI-powered tailoring.
    Currently, it simply merges the master profile data with the company/job information.

    Args:
        profile: The user's master profile
        company: The company and job information

    Returns:
        A tailored resume as markdown text
    """

    # Extract key information
    name = profile.full_name
    email = profile.email
    phone = profile.phone or "N/A"
    location = profile.location or "N/A"
    linkedin = profile.linkedin_url or ""
    portfolio = profile.portfolio_url or ""
    github = profile.github_url or ""

    # Build the resume
    resume_parts = []

    # Header
    resume_parts.append(f"# {name}\n")
    resume_parts.append(f"**Email:** {email} | **Phone:** {phone} | **Location:** {location}\n")

    if linkedin:
        resume_parts.append(f"**LinkedIn:** {linkedin}")
    if portfolio:
        resume_parts.append(f" | **Portfolio:** {portfolio}")
    if github:
        resume_parts.append(f" | **GitHub:** {github}")
    resume_parts.append("\n\n")

    # Target Position
    resume_parts.append(f"## Target Position\n")
    resume_parts.append(f"**{company.job_title}** at **{company.company_name}**\n\n")

    # Professional Summary
    if profile.professional_summary:
        resume_parts.append("## Professional Summary\n")
        resume_parts.append(f"{profile.professional_summary}\n\n")

    # Work Experience
    if profile.work_experience:
        resume_parts.append("## Work Experience\n")
        resume_parts.append(f"{profile.work_experience}\n\n")

    # Education
    if profile.education:
        resume_parts.append("## Education\n")
        resume_parts.append(f"{profile.education}\n\n")

    # Technical Skills
    if profile.technical_skills:
        resume_parts.append("## Technical Skills\n")
        resume_parts.append(f"{profile.technical_skills}\n\n")

    # Projects
    if profile.projects:
        resume_parts.append("## Projects\n")
        resume_parts.append(f"{profile.projects}\n\n")

    # Certifications
    if profile.certifications:
        resume_parts.append("## Certifications\n")
        resume_parts.append(f"{profile.certifications}\n\n")

    # Achievements
    if profile.achievements:
        resume_parts.append("## Achievements\n")
        resume_parts.append(f"{profile.achievements}\n\n")

    # Additional sections
    if profile.languages:
        resume_parts.append("## Languages\n")
        resume_parts.append(f"{profile.languages}\n\n")

    if profile.volunteer_work:
        resume_parts.append("## Volunteer Work\n")
        resume_parts.append(f"{profile.volunteer_work}\n\n")

    # Footer note
    resume_parts.append("\n---\n")
    resume_parts.append(f"*This resume was tailored for {company.company_name} - {company.job_title}*\n")
    resume_parts.append("*Generated by Resume Vault (Mock Tailor - AI integration coming soon)*\n")

    return "".join(resume_parts)


def extract_keywords(text: str, top_n: int = 10) -> str:
    """
    Simple keyword extraction from text.
    Returns comma-separated keywords.

    TODO: Improve with NLP libraries like spaCy or use AI for better keyword extraction.
    """
    if not text:
        return ""

    # Simple approach: get most common words (excluding common words)
    common_words = {
        "the", "a", "an", "and", "or", "but", "in", "on", "at", "to", "for",
        "of", "with", "by", "from", "as", "is", "was", "are", "were", "be",
        "been", "being", "have", "has", "had", "do", "does", "did", "will",
        "would", "should", "could", "may", "might", "must", "can", "this",
        "that", "these", "those", "i", "you", "he", "she", "it", "we", "they"
    }

    words = text.lower().split()
    word_freq = {}

    for word in words:
        # Remove punctuation
        word = word.strip(".,!?;:()[]{}\"'")
        if len(word) > 3 and word not in common_words:
            word_freq[word] = word_freq.get(word, 0) + 1

    # Sort by frequency
    sorted_words = sorted(word_freq.items(), key=lambda x: x[1], reverse=True)
    top_words = [word for word, freq in sorted_words[:top_n]]

    return ", ".join(top_words)
